### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by devtronic** [vince-nyanga/CleanArchitectureExample#1]
Hi, I've read your tutorial on medium. It's very well explained, thank you.

I'm new in this topic and I've some questions about your source
- I would name this interface IWeatherApi since the naming inside since the repository needs an api for fetching weather data. What do you think about it? https://github.com/vince-nyanga/CleanArchitectureExample/blob/master/Data/Api/IApi.cs
- Do you have a better approach for structuring the code? I prefer the screaming architecture so I'm trying out this  "hybrid archtitecture" at the moment:
```
src/
|- data
   |- repository  <- Contains the implementations
      |- ApiWeatherRepository.src
|- domain
   |- entity <- Contains your business objects
      |- Weather.src
   |- repository <- Contains the interfaces for dependency inversion
      |- WeatherRepository.src
|- feature1
   |- data <- optional; data layer; only contains things for this feature
   |- domain <- optional; domain layer; only contains things for this feature
   |- presentation
      |- presenter
         |- Feature1Presenter.src
      |- view
         |- Feature1View.src
|- feature2
   |- presentation
      |- presenter
         |- Feature2Presenter.src
      |- view
         |- Feature2View.src
|- ...
```
| **Pros** | **Cons** |
| -------- | --------- |
| Screaming Architecture | If you look for a piece of code you've to search in multiple places |
| Layer based structure |  |
| Scalable / No messy big directories |   |

What do you think about it?

Can you give an example, how you would implement the presenter / view logic?
![Image](https://learning.oreilly.com/library/view/pr-clean-architecture/9783958457263/Images/kap22_bild02_cleanarch.jpg)

**Comment by vince-nyanga** [comment]
Hi,
I'm also fairly new to this and still learning.
I agree with you -- the interface should be named `IWeatherApi`. With respect to the code structure, like you said, when one would have to search in multiple locations to find a piece of code even though it will scale very well. In my opinion your code structure works well except for that one disadvantage.

**Comment by devtronic** [comment]
Thanks for your reply 🙂
